### ISSUE TITLE
How to get working in Vue project

### ISSUE THREAD

**Issue by LovelyAndy** [jagaad/vue-hubspot-form#1]
Hello there, I am trying to use this library, but cannot seem to get the form to render. Do you have any examples of getting this to work properly?

I made a codesandbox to try it out, because I couldn't find any examples anywhere.

https://codesandbox.io/s/festive-tree-btvl1x?file=/src/components/Form.vue

For context, I am trying to use Hubspot forms for my app and need to edit the style.

Cheers!

**Comment by unrevised6419** [comment]
Fixed in https://github.com/jagaad/vue-hubspot-form/releases/tag/v2.2.3

@LovelyAndy please update to `v2.2.3`. In your example, I updated to `v2.2.3` and it works

For examples please see the README file, and adjust the props in the right way.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/1881266/202544328-514ace87-e18f-4867-b6c7-926ced901c34.png">
